// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRS8NMMsItHHFFFK1edAv7xyhBQY6VuQg',
    appId: '1:1029978660188:web:a1e25f0686bb36222e7599',
    messagingSenderId: '1029978660188',
    projectId: 'kecerdasanbuatan-4c881',
    authDomain: 'kecerdasanbuatan-4c881.firebaseapp.com',
    databaseURL: 'https://kecerdasanbuatan-4c881-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kecerdasanbuatan-4c881.firebasestorage.app',
    measurementId: 'G-8W4RRQ700N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAks4HFrZd_y2nh6apDaoMaQzjo2YqvAvc',
    appId: '1:1029978660188:android:1d9ce7998bb9fd332e7599',
    messagingSenderId: '1029978660188',
    projectId: 'kecerdasanbuatan-4c881',
    databaseURL: 'https://kecerdasanbuatan-4c881-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kecerdasanbuatan-4c881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGAiw3-YmnqjDqQf9tmupJQe5lXnXJ-f8',
    appId: '1:1029978660188:ios:5a794cbd00edcf632e7599',
    messagingSenderId: '1029978660188',
    projectId: 'kecerdasanbuatan-4c881',
    databaseURL: 'https://kecerdasanbuatan-4c881-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kecerdasanbuatan-4c881.firebasestorage.app',
    iosBundleId: 'com.example.kecerdasanbuatan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGAiw3-YmnqjDqQf9tmupJQe5lXnXJ-f8',
    appId: '1:1029978660188:ios:5a794cbd00edcf632e7599',
    messagingSenderId: '1029978660188',
    projectId: 'kecerdasanbuatan-4c881',
    databaseURL: 'https://kecerdasanbuatan-4c881-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kecerdasanbuatan-4c881.firebasestorage.app',
    iosBundleId: 'com.example.kecerdasanbuatan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRS8NMMsItHHFFFK1edAv7xyhBQY6VuQg',
    appId: '1:1029978660188:web:ae48e84d5dd10eeb2e7599',
    messagingSenderId: '1029978660188',
    projectId: 'kecerdasanbuatan-4c881',
    authDomain: 'kecerdasanbuatan-4c881.firebaseapp.com',
    databaseURL: 'https://kecerdasanbuatan-4c881-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kecerdasanbuatan-4c881.firebasestorage.app',
    measurementId: 'G-HNM5XZVDRM',
  );

}